cookie:
  expiry_days: 7
  key: 928a6f51083a88ba71d2c058fd01c02f81beb40263d0c25f
  name: darkpool_resort_portoseguro_auth
credentials:
  usernames:
    darkpool:
      email: negocios@darkpool.com.br
      failed_login_attempts: 0
      logged_in: false
      name: DarkPool Intermediação de Ativos
      password: $2b$12$BgqDAA7Vte7EbMdySl/lj.OORlJ0TuJNcmARiIDVQhd/hz19X4jnO
      role: master
    osmar.aoki:
      email: aoki_100@hotmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Osmar Aoki
      password: $2b$12$jiWtVmfFczW5vXNQhcXMO.zvX2yiF7z8kVKtjJTm7bAefbS03TcOq
      role: user
    paulo.molina:
      email: ''
      failed_login_attempts: 0
      logged_in: false
      name: Paulo Molina
      password: $2b$12$VoKqTvWkC7Rdj7gZYz8rf.hrIrudA6cyDLG8WyAo/4psuGIF6nAgS
      role: user
